import dotenv from "dotenv";
import express from "express";
import bodyParser from "body-parser";
import mongodb from "mongodb";
import cors from "cors";
import { sendConfirmationEmail, sendUnsubEmail } from "./veriEmailSender.js";
import path from "path";
import { fileURLToPath } from "url";
import cryptoRandomString from "crypto-random-string";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const { MongoClient } = mongodb;
const app = express();
dotenv.config();
app.use(bodyParser.json());
app.use(cors());

const PORT = process.env.PORT || 8080;


if (process.env.NODE_ENV === "production") {
  app.use(express.static("../frontend/build"));
}

MongoClient.connect(
  `mongodb+srv://siboyang:${process.env.db_password}@cluster0.iot5g.mongodb.net/MailingList?retryWrites=true&w=majority`,
  { useUnifiedTopology: true }
)
  .then((client) => {
    console.log("Connected to Database");
    const db = client.db("MailingList");
    const users = db.collection("list");

    /**
     * request body:
     * {active: boolean, active_code: string (active code is generated by frontend)}
     */
    app.post("/subscribe", async (req, res) => {
      try {
        const new_sub = req.body;
        if (new_sub.base === new_sub.target) {
          res.status(500).json({ error: "Base and target cannot be the same" });
          return;
        }
        new_sub.active = false;
        new_sub.activeCode = cryptoRandomString({
          length: 20,
          type: "url-safe",
        });
        new_sub._id = new_sub.email;
        new_sub.daysLeft = 1; // start receiving the first email the next day
        const created_user = await users.insertOne(new_sub);
        console.log("One user subscribed. Waiting for verification");
        sendConfirmationEmail(
          new_sub.firstName,
          new_sub.email,
          new_sub.activeCode
        );
        res.status(201).json(created_user);
      } catch (e) {
        if (e.code === 11000) {
          res.status(409).json({ error: "Email already exist" });
        } else {
          res.status(500).json({ error: "Something goes wrong." });
        }
      }
    });

    app.delete("/unsubscribe", async (req, res) => {
      try {
        const user = req.body;
        const user_removed = await users.findOneAndDelete(user);
        if (user_removed.value === null) {
          res.status(404).json({ error: "Information given doesn't exist" });
        } else {
          sendUnsubEmail(user.firstName, user.email);
          console.log("one user unsubscribed.");
          res.status(200).json(user_removed.value);
        }
      } catch (e) {
        console.log(e);
      }
    });

    app.get("/verification", async (req, res) => {
      try {
        const email = req.query.email;
        const code = req.query.code;
        const user = await users.findOne({ _id: email });
        if (user.activeCode === code) {
          await users.updateOne({ _id: email }, { $set: { active: true } });
          console.log("One user verified.");
          res
            .status(200)
            .sendFile(path.join(__dirname + "/views/success.html"));
        } else {
          res.status(200).sendFile(path.join(__dirname + "/views/fail.html"));
        }
      } catch (e) {
        console.log(e);
        res.status(500).json({ error: "Something goes wrong." });
      }
    });
  })
  .catch((error) => console.error(error));

app.listen(PORT, () => {
  console.log(`listening on ${PORT}`);
});
